ifmoradas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moradias.urls'))
]

moradias/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home, name='home'),
    path('novo/', views.novo, name='novo'),
    path('detalhes/<int:pk>/', views.detalhes, name='detalhes'),
    path('editar/<int:pk>/', views.editar, name='editar'),
    path('remover/<int:pk>/', views.remover, name='remover'),

    path('create/', views.create, name='create'),
    path('update/<int:pk>/', views.update, name='update'),

    path('erro/', views.erro, name='erro'),

    path('telaLogin', views.telaLogin, name='telaLogin'),
    path('telaRegistro', views.telaRegistro, name='telaRegistro'),
    path('registrar', views.registrar, name='registrar'),
    path('logar', views.logar, name='logar'),
    path('logout', views.deslogar, name='logout'),

    path('telaImagem/<int:pk>/', views.telaImagem, name='telaImagem'),
    path('novaImagem', views.novaImagem, name="novaImagem"),

    path('meusImoveis', views.meusImoveis, name="meusImoveis"),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

moradias/models.py
from django.db import models
from django.contrib.auth.models import User


class Moradia(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.CharField(max_length=500)
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    dono = models.IntegerField(null=True)


class Imagem(models.Model):
    imovel = models.IntegerField(null=True)
    arquivo = models.FileField(upload_to=f'imoveis/')

moradias/forms.py
from django import forms
from django.forms import ModelForm
from moradias.models import Moradia


class MoradiaForm(ModelForm):
    class Meta:
        model = Moradia
        fields = ['nome', 'descricao', 'valor', 'dono']


class ImagemForm(forms.Form):
    arquivo = forms.FileField(label='Selecione um arquivo')

moradias/views.py
from django.forms.widgets import DateTimeBaseInput
from django.shortcuts import redirect, render
from moradias.forms import MoradiaForm, ImagemForm
from moradias.models import Moradia, Imagem
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User


def erro(request, mensagem):
    if not request.user.is_authenticated: return redirect('telaLogin')
    data = {}
    data['erro'] = mensagem
    return render(request, 'erro.html', data)


def home(request):
    if not request.user.is_authenticated: return redirect('telaLogin')
    data = {}

    # Pegar todos os imóveis e fazer páginas
    search = request.GET.get('search')
    if search:
        data['moradias'] = Moradia.objects.filter(nome__icontains=search)
        data['search'] = True
    else:
        data['moradias'] = Moradia.objects.all()

    if len(data['moradias']) > 0:
        paginator = Paginator(data['moradias'], 8)
        pages = request.GET.get('page')
        data['moradias'] = paginator.get_page(pages)

    # Pegar o último imóvel para colocar em destaque
    try:
        data['recente'] = Moradia.objects.order_by('-id')[0]
        data['imagemRecente'] = Imagem.objects.filter(imovel=data['recente'].id).order_by('-id')[0]
    except:
        print("Erro")
    imagens = []
    for moradia in data['moradias']:
        try:
            imagens.append(Imagem.objects.filter(imovel=moradia.id).order_by('-id')[0])
        except:
            print("Erro")
    data['imagens'] = imagens 
    return render(request, 'index.html', data)


def novo(request):
    if not request.user.is_authenticated: return redirect('telaLogin')
    data = {}
    data['form'] = MoradiaForm()
    return render(request, 'form.html', data)


def telaImagem(request, pk):
    if not request.user.is_authenticated: return redirect('telaLogin')
    data = {}
    data['form'] = ImagemForm()
    data['imovel'] = pk
    return render(request, 'imagem.html', data)


def novaImagem(request):
    if not request.user.is_authenticated: return redirect('telaLogin')
    try:
        nova_imagem1 = Imagem(arquivo=request.FILES['imagem1'], imovel=request.POST['imovel'])
        nova_imagem1.save()
        nova_imagem2 = Imagem(arquivo=request.FILES['imagem2'], imovel=request.POST['imovel'])
        nova_imagem2.save()
        nova_imagem3 = Imagem(arquivo=request.FILES['imagem3'], imovel=request.POST['imovel'])
        nova_imagem3.save()
        nova_imagem4 = Imagem(arquivo=request.FILES['imagem4'], imovel=request.POST['imovel'])
        nova_imagem4.save()
    except:
        print("Erro")

    return redirect('home')


def create(request):
    if not request.user.is_authenticated: return redirect('telaLogin')
    form = MoradiaForm(request.POST, request.FILES)
    print(form)
    if form.is_valid():
        retorno = form.save()
        return redirect("telaImagem", retorno.id)
    else:
        return erro(request, form)


def detalhes(request, pk):
    if not request.user.is_authenticated: return redirect('telaLogin')
    data = {}
    # Pega o imóvel escolhido
    data['imovel'] = Moradia.objects.get(pk=pk)

    # Seleciona os 5 imoveis mais recentes
    data['moradias'] = Moradia.objects.order_by('-id')[:4]

    # Pega as últimas 5 fotos desse imóvel
    data['fotos'] = Imagem.objects.filter(imovel=pk).order_by('-id')[1:3]

    data['principal'] = Imagem.objects.filter(imovel=pk).order_by('-id')[0]
    print(data['imovel'].dono)
    data['dono'] = User.objects.filter(id=data['imovel'].dono)[0]

    imagens = []
    for moradia in data['moradias']:
        try:
            imagens.append(Imagem.objects.filter(imovel=moradia.id).order_by('-id')[0])
        except:
            print("Erro")

    data['imagens'] = imagens
    return render(request, 'detalhes.html', data)


def editar(request, pk):
    if not request.user.is_authenticated: return redirect('telaLogin')
    data = {}
    data['moradias'] = Moradia.objects.get(pk=pk)
    data['form'] = MoradiaForm(instance=data['moradias'])
    data['valor'] = str(data['moradias'].valor).replace(",", ".")
    return render(request, 'form.html', data)


def update(request, pk):
    if not request.user.is_authenticated: return redirect('telaLogin')
    data = {}
    data['moradias'] = Moradia.objects.get(pk=pk)
    if request.user.id == data['moradias'].dono: form = MoradiaForm(request.POST or None, instance=data['moradias'])
    if form.is_valid():
        form.save()
        return redirect('home')
    else:
        return erro(request, form.errors)


def remover(request, pk):
    if not request.user.is_authenticated: return redirect('telaLogin')
    db = Moradia.objects.get(pk=pk)
    if request.user.id == db.dono: db.delete()
    return redirect('home')


def telaLogin(request):
    return render(request, 'login.html')


def logar(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('home')
    else:
        return erro(request, "Não foi possível realizar o login utilizando essas credenciais.")


def deslogar(request):
    if not request.user.is_authenticated: return redirect('telaLogin')
    logout(request)
    return redirect('home')


def telaRegistro(request):
    return render(request, 'register.html')


def registrar(request):
    usuario = User.objects.create_user(
        request.POST['email'], request.POST['email'], request.POST['password'])
    usuario.first_name = request.POST['first_name']
    usuario.last_name = request.POST['last_name']
    usuario.save()
    return redirect('home')

def meusImoveis(request):
    if not request.user.is_authenticated: return redirect('telaLogin')
    data = {}

    data['moradias'] = Moradia.objects.filter(dono=request.user.id)

    if len(data['moradias']) > 0:
        paginator = Paginator(data['moradias'], 8)
        pages = request.GET.get('page')
        data['moradias'] = paginator.get_page(pages)

    imagens = []
    for moradia in data['moradias']:
        try:
            imagens.append(Imagem.objects.filter(imovel=moradia.id).order_by('-id')[0])
        except:
            print("Erro")
    data['imagens'] = imagens 
    
    return render(request, 'proprio.html', data)

moradias/templates/_footer.html
<footer class="footer bottom bg-success text-white py-4 mt-5">
	<div class="container">
		<div class="row align-items-center justify-content-center">
			<div class="col-md-6 col-sm-12 text-md-start text-sm-center">
				<hr />
				<address>
					<strong>IFMoradas</strong>
					<br /><i class="bi bi-geo-alt"></i> Av. Fahdo Thomé, n°3000 <br />Champagnat | Caçador - SC - Cep 89500-000
				</address>
				<hr />
				<address>
					<i class="bi bi-telephone"></i><abbr> Fixo: </abbr>
					<a style="text-decoration: none; color: white" href="tel:05549998048595">(49) 9 9804-8595</a>
					<br />
					<i class="bi bi-envelope"></i><abbr> E-mail: </abbr>
					<a class="text-decoration-none text-white" href="mailto:ifmoradas@hotmail.com">ifmoradas@hotmail.com</a>
				</address>
			</div>
			<div class="col-md-6 col-sm-12">
				<iframe
					class="col-12 shadow-lg p-3 bg-body rounded"
					src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3561.9045426748985!2d-51.04096358525241!3d-26.779312594102862!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94e6cbd8b362872d%3A0x219cb0ef3ca5f2e0!2zSUZTQyBDw6JtcHVzIENhw6dhZG9y!5e0!3m2!1spt-BR!2sbr!4v1636132357607!5m2!1spt-BR!2sbr"
					frameborder="0"
					allowfullscreen=""
					aria-hidden="false"
					tabindex="0"
				></iframe>
			</div>
		</div>
		<hr />
		<div class="container">
			<div class="social d-flex justify-content-center">
				<a type="button" target="_blank" class="btn btn-close-white mx-2" href="https://github.com/AnthonyLeier"
					><i class="bi bi-instagram"></i
				></a>
				<a type="button" target="_blank" class="btn btn-close-white mx-2" href="https://www.facebook.com/IFSC.CACADOR"
					><i class="bi bi-facebook"></i
				></a>
				<a type="button" target="_blank" class="btn btn-close-white mx-2" href="https://github.com/AnthonyLeier"
					><i class="bi bi-github"></i
				></a>
			</div>
			<div class="row align-items-center justify-content-center text-center">
				<div class="col-lg-4">Copyright © IFMoradas 2021</div>
			</div>
		</div>
	</div>
</footer>

moradias/templates/_navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-success text-white">
	<div class="container px-4 px-lg-5">
		<a class="navbar-brand text-white" href="/">IFMoradas</a>
		<button
			class="navbar-toggler"
			type="button"
			data-bs-toggle="collapse"
			data-bs-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<div class="navbar-nav me-auto mb-2 mb-lg-0"></div>
			<form class="d-flex me-auto" action="/" method="get">
				<input class="form-control me-2" type="search" placeholder="Pesquisar" aria-label="Search" id="search" name="search" />
				<button class="btn btn-outline-light" type="submit"><i class="bi bi-search"></i></button>
			</form>
			{% if user.is_authenticated %}
			<div class="dropdown">
				<button
					class="btn btn-outline-light dropdown-toggle"
					type="button"
					id="dropdownMenuButton1"
					data-bs-toggle="dropdown"
					aria-expanded="false"
				>
					{{user.get_full_name}}
				</button>
				<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
					<li><a class="dropdown-item" href="/novo">Adicionar novo imóvel</a></li>
					<li><a class="dropdown-item" href="/meusImoveis">Ver seus imóveis</a></li>
					<li><a class="dropdown-item" href="/logout">Sair</a></li>
				</ul>
			</div>
			{% else %}
			<a href="/telaLogin" class="text-decoration-none text-reset"><i class="bi bi-person-circle"></i></a>
			{% endif %}
		</div>
	</div>
</nav>

moradias/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>IFMoradas</title>

		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
			crossorigin="anonymous"
		/>

		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css" />
	</head>
	<body>
		{% include '_navbar.html' %} {% block conteudo %} {% endblock %} {% include '_footer.html' %}

		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
			crossorigin="anonymous"
		></script>
	</body>
</html>

moradias/templates/detalhes.html
{% extends 'base.html' %} {% block conteudo %} {% load static %}

<section>
	<div class="container px-4 px-lg-5 my-5 shadow-lg p-3 mb-5 bg-body rounded">
		<div class="row gx-4 gx-lg-5 align-items-center">
			<div class="col-md-6">
				<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
					<div class="carousel-inner">
						<div class="carousel-item active">
							<img
								class="card-img-top mb-5 mb-md-0"
								src="{% get_media_prefix %}{{principal.arquivo}}"
								style="max-height: 350px"
							/>
						</div>
						{% for foto in fotos %}
						<div class="carousel-item">
							<img
								class="card-img-top mb-5 mb-md-0"
								src="{% get_media_prefix %}{{foto.arquivo}}"
								alt="{{foto.arquivo}}"
								style="max-height: 350px"
							/>
						</div>
						{% endfor %}
					</div>
					<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Anterior</span>
					</button>
					<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Posterior</span>
					</button>
				</div>
			</div>
			<div class="col-md-6">
				<h1 class="display-5 fw-bolder">{{imovel.nome}}</h1>
				<div class="fs-5 mb-5">
					<span>R${{imovel.valor}}</span>
				</div>
				<p class="lead">{{imovel.descricao}}</p>
				<div class="d-flex mt-5">
					<div class="btn-group" role="group">
						<a
							href="mailto:{{dono.email}}"
							class="btn btn-outline-success"
							data-bs-toggle="tooltip"
							data-bs-placement="top"
							title="Entrar em contato"
							><i class="bi bi-arrow-right me-1"></i> Entrar em contato</a
						>
						{% if user.id == imovel.dono %}
						<a
							href="/editar/{{imovel.id}}"
							class="btn btn-success"
							data-bs-toggle="tooltip"
							data-bs-placement="top"
							title="Editar Imóvel"
							><i class="bi bi-gear-fill"></i
						></a>
						<a
							href="/telaImagem/{{imovel.id}}"
							class="btn btn-success"
							data-bs-toggle="tooltip"
							data-bs-placement="top"
							title="Gerenciador de Imagens"
							><i class="bi bi-image-fill"></i
						></a>
						<a
							href="#"
							class="btn btn-danger"
							data-bs-toggle="tooltip"
							data-bs-placement="top"
							title="Remover Imóvel"
							onclick="remover({{imovel.id}})"
							><i class="bi bi-x-octagon"></i
						></a>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="py-5 bg-light">
	<div class="container px-4 px-lg-5 mt-5">
		<h2 class="fw-bolder mb-4">Outros Imóveis</h2>
		<div class="container">
			<div class="row" id="geral">
				{% for imovel in moradias %}
				<div class="col-md-3 col-sm-6 my-2" onclick="location.href='/detalhes/{{imovel.id}}';">
					<div class="card">
						{% for imagem in imagens %} {% if imovel.id == imagem.imovel %}
						<img src="{% get_media_prefix %}{{imagem.arquivo}}" class="card-img-top" style="max-height: 150px" />
						{% endif %} {% endfor %}
						<div class="card-body">
							<h5 class="card-title">{{imovel.nome}}</h5>
							<b class="card-text text-right">R$ {{imovel.valor}}</b>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</section>
<script>
	function remover(id){
		var resposta = confirm('Deseja apagar o item?')

		if (resposta){
			window.location.href = `/remover/${id}`;
		}
	}
</script>
{% endblock %}

moradias/templates/erro.html
{% extends 'base.html' %} {% block conteudo %}
<div class="container my-5">
	<h1 class="text-danger my-5">Ocorreu um erro ao executar essa ação!</h1>
	<pre class="my-5">{{erro}}</pre>
</div>
{% endblock %}

moradias/templates/form.html
{% extends 'base.html' %} {% block conteudo %}
<div class="container shadow-lg p-3 my-3 bg-body rounded">
	<div class="col-8 m-auto pt-2 pb-2 text-center">
		<h1>Formulário de Imóvel</h1>
	</div>
	<div class="col-8 m-auto pt-2>s pb-2 text-center mt-3">
		<form name="form" id="form" action="{% if moradias %} /update/{{moradias.id}}/ {% else %} /create/ {%endif%}" method="post">
			{% csrf_token %}
			<input type="hidden" value="{{user.id}}" name="dono" />

			<div class="form-floating mb-3">
				<input
					type="text"
					class="form-control"
					id="floatingInput"
					placeholder="text"
					name="nome"
					maxlength="50"
					required
					id="id_nome"
					value="{{moradias.nome}}"
				/>
				<label for="floatingInput">Título</label>
			</div>
			<div class="form-floating mb-3">
				<input
					type="text"
					class="form-control"
					id="floatingInput"
					placeholder="text"
					name="descricao"
					maxlength="500"
					required
					id="id_descricao"
					value="{{moradias.descricao}}"
				/>
				<label for="floatingInput">Descrição</label>
			</div>
			<div class="form-floating mb-3">
				<input
					type="number"
					class="form-control"
					id="floatingInput"
					placeholder="text"
					name="valor"
					step="0.01"
					required
					id="id_valor"
					value="{{valor}}"
				/>
				<label for="floatingInput">Valor</label>
			</div>
			<div class="d-grid gap-2 d-md-block">
				<input type="submit" class="btn btn-success" value="Salvar" />
			</div>
		</form>
	</div>
</div>
{% endblock %}

moradias/templates/imagem.html
{% extends 'base.html' %} {% block conteudo %}
<div class="container shadow-lg p-3 my-3 bg-body rounded">
	<div class="col-8 m-auto pt-2 pb-2 text-center">
		<h1>Gerenciador de Imagens</h1>
	</div>
	<div class="col-8 m-auto pt-2>s pb-2 text-center mt-3">
		<form action="{% url 'novaImagem' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<input type="hidden" name="imovel" value="{{imovel}}" />
			<div class="mb-3">
				<input class="form-control" type="file" id="formFile" name="imagem1" />
			</div>
			<div class="mb-3">
				<input class="form-control" type="file" id="formFile" name="imagem2" />
			</div>
			<div class="mb-3">
				<input class="form-control" type="file" id="formFile" name="imagem3" />
			</div>
			<div class="mb-3">
				<input class="form-control" type="file" id="formFile" name="imagem4" />
			</div>
			<button class="btn btn-success" type="submit">Salvar</button>
		</form>
	</div>
</div>

{% endblock %}

moradias/templates/index.html
{% extends 'base.html' %} {% block conteudo %}
{% load static %}
{% if not search %}
<section class="pt-5">
	<div class="container px-5">
		<div class="card border-1 shadow rounded-3 overflow-hidden">
			<div class="card-body p-0">
				<div class="row gx-0">
					<div class="col-lg-6 col-xl-5 py-lg-5">
						<div class="p-4 p-md-5">
							<div class="badge bg-primary bg-gradient rounded-pill mb-2">Novidades</div>
							<div class="h2 fw-bolder">Novos imóveis</div>
							<p>{{recente.descricao}}</p>
							<a class="stretched-link text-decoration-none" href="/detalhes/{{recente.id}}">
								Ver novidades
								<i class="bi bi-arrow-right"></i>
							</a>
						</div>
					</div>
					<div class="col-lg-6 col-xl-7">
						<img class="img-fluid col-12 max-width: 100% justify-content-center" src="{% get_media_prefix %}{{imagemRecente.arquivo}}">
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endif %}
<div class="container pt-5">
	<div class="row" id="geral">
		{% for imovel in moradias %}
		<div class="col-md-3 col-sm-6 my-2" onclick="location.href='/detalhes/{{imovel.id}}';">
			<div class="card">
				{% for imagem in imagens %}
					{% if imovel.id == imagem.imovel %}
						<img src="{% get_media_prefix %}{{imagem.arquivo}}" class="card-img-top" style="max-height: 150px" />
					{% endif %}
				{% endfor %}
				<div class="card-body">
					<h5 class="card-title">{{imovel.nome}}</h5>
					<b class="card-text text-right">R$ {{imovel.valor}}</b>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
<div class="container my-4">
	<div class="row text-center">
		<ul class="pagination justify-content-center shadow-lg p-3 my-3 bg-body rounded">

			<li class="page-item"><a class="page-link text-success" href="?page=1">Primeiro</a></li>

			{% if moradias.has_previous %}
			<li class="page-item"><a class="page-link" href="?page={{moradias.previous_page_number}}">Anterior</a></li>
			{% else %}
			<li class="page-item"><a class="page-link text-muted" href="#">Anterior</a></li>
			{% endif %}

			<li class="page-item"><a class="page-link" href="?page={{moradias.number}}">{{moradias.number}}</a></li>

			{% if moradias.has_next %}
			<li class="page-item"><a class="page-link" href="?page={{moradias.next_page_number}}">Próximo</a></li>
			{% else %}
			<li class="page-item"><a class="page-link text-muted" href="#">Próximo</a></li>
			{% endif %}
			
			<li class="page-item"><a class="page-link text-success" href="?page={{moradias.paginator.num_pages}}">Último</a></li>
		</ul>
	</div>
</div>

{% endblock %}

moradias/templates/login.html
{% extends 'base.html' %} {% block conteudo %}
{% load static %}
<main class="form-signin">
	<div class="container" style="margin-top: 5%">
		<div class="row">
			<div class="col-3"></div>
			<div class="col-6">
				<form class="" action="/logar" method="post">
					{% csrf_token %}
					<div class="text-center">
						<img class="mb-4" src="{% static 'img/ifsc.png' %}" alt="" width="72" height="72" />
						<h1 class="h3 mb-3 fw-normal">Login IFMoradas</h1>
					</div>
					<div class="form-floating mt-5">
						<input type="text" name="username" class="form-control" id="floatingInput" placeholder="email@gmail.com" />
						<label for="floatingInput">Informe seu email</label>
					</div>
					<div class="form-floating mt-3">
						<input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password" />
						<label for="floatingPassword">Informe sua senha</label>
					</div>
					<button class="w-100 btn btn-lg btn-success mt-3" type="submit">Acessar</button>
					<p class="text-center pt-3"><a class="text-decoration-none text-reset" href="/telaRegistro">Registre-se agora!</a></p>
					<p class="mt-5 mb-3 text-muted text-center">&copy; 2021</p>
				</form>
			</div>
			<div class="col-3"></div>
		</div>
	</div>
</main>
{% endblock %}

moradias/templates/proprio.html
{% extends 'base.html' %} {% block conteudo %} {% load static %}
<div class="container pt-5">
	<div class="row" id="geral">
		{% for imovel in moradias %}
		<div class="col-md-3 col-sm-6 my-2" onclick="location.href='/detalhes/{{imovel.id}}';">
			<div class="card">
				{% for imagem in imagens %} {% if imovel.id == imagem.imovel %}
				<img src="{% get_media_prefix %}{{imagem.arquivo}}" class="card-img-top" style="max-height: 150px" />
				{% endif %} {% endfor %}
				<div class="card-body">
					<h5 class="card-title">{{imovel.nome}}</h5>
					<b class="card-text text-right">R$ {{imovel.valor}}</b>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
<div class="container my-4">
	<div class="row text-center">
		<ul class="pagination justify-content-center shadow-lg p-3 my-3 bg-body rounded">
			<li class="page-item"><a class="page-link text-success" href="?page=1">Primeiro</a></li>

			{% if moradias.has_previous %}
			<li class="page-item"><a class="page-link" href="?page={{moradias.previous_page_number}}">Anterior</a></li>
			{% else %}
			<li class="page-item"><a class="page-link text-muted" href="#">Anterior</a></li>
			{% endif %}

			<li class="page-item"><a class="page-link" href="?page={{moradias.number}}">{{moradias.number}}</a></li>

			{% if moradias.has_next %}
			<li class="page-item"><a class="page-link" href="?page={{moradias.next_page_number}}">Próximo</a></li>
			{% else %}
			<li class="page-item"><a class="page-link text-muted" href="#">Próximo</a></li>
			{% endif %}

			<li class="page-item"><a class="page-link text-success" href="?page={{moradias.paginator.num_pages}}">Último</a></li>
		</ul>
	</div>
</div>
{% endblock %}

moradias/templates/register.html
{% extends 'base.html' %} {% block conteudo %} {% load static %}
<main class="form-signin">
	<div class="container px-md-5" style="margin-top: 5%">
		<form class="row px-md-5 g-3 pb-5 needs-validation" action="/registrar" method="post">
			{% csrf_token %}
			<div class="col-12 text-center">
				<img class="mb-4" src="{% static 'img/ifsc.png' %}" alt="" width="72" height="72" />
				<h1 class="h3 mb-3 fw-normal">Registro IFMoradas</h1>
			</div>
			<div class="col-md-4">
				<label for="validationCustom01" class="form-label">Nome</label>
				<input type="text" class="form-control" id="validationCustom01" name="first_name" required />
			</div>
			<div class="col-md-4">
				<label for="validationCustom02" class="form-label">Sobrenome</label>
				<input type="text" class="form-control" id="validationCustom02"  name="last_name" required />
			</div>
			<div class="col-md-4">
				<label for="validationCustom02" class="form-label">Telefone</label>
				<input type="tel" class="form-control" id="validationCustom02" name="telefone" required />
			</div>
			<div class="col-md-12">
				<div class="form-floating">
					<input type="email" class="form-control" id="floatingInput" name="email" placeholder="nome@exemplo.com" />
					<label for="floatingInput">E-mail</label>
				</div>
			</div>
			<div class="col-md-12">
				<div class="form-floating">
					<input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Senha" />
					<label for="floatingPassword">Senha</label>
				</div>
			</div>
			<div class="col-12">
				<button class="btn btn-success float-end" type="submit">Registrar</button>
			</div>
		</form>
	</div>
</main>
{% endblock %}